//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplUserRegandLogin.ViewModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class TestImgDB
    {
        [Required]
        public int ImageID { get; set; }

        public string ImageName { get; set; }
        [Display(Name = "Upload Image")]

        public string ImagePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
